#!/usr/bin/env bash

set -o pipefail -o errexit

# Steamlaunchy
# A tiny wrapper to programmatically launch third-party windows applications from within Steam

# Usage: steamlaunchy <path/to/exe>

# STEAMLAUNCHY_CONFIG_HOME           Defaults to '~/.config/steamlaunchy'
# STEAMLAUNCHY_DATA_HOME             Defaults to '~/.local/share/steamlaunchy'
# STEAMLAUNCHY_CONF                  Override Steamlaunchy config. A config file is optional
# STEAMLAUNCHY_DEBUG                 Set to '1' to increase logging
# STEAMLAUNCHY_PROTON_PATH           Override Proton versions available to Steamlaunchy. By default it searches the Steam installation dir. Comma delimited string of proton dir paths
# STEAMLAUNCHY_PROTON_VERSION        Override default Proton version. By default the lastest stable Proton version is selected
# STEAMLAUNCHY_PROTON_BIN            Override absolute path to Proton executable
# STEAMLAUNCHY_PROTON_BIN_NAME       Override Proton executable basename
# STEAMLAUNCHY_INCLUDE_EXPERIMENTAL  Set to `1` to include non-semantic Proton versions in Proton version selection
# STEAMLAUNCHY_APPLICATION_PREFIX    Override the application prefix in STEAMLAUNCHY_DATA_HOME

STEAMLAUNCHY_CONFIG_HOME="${STEAMLAUNCHY_CONFIG_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}/steamlaunchy}"
STEAMLAUNCHY_DATA_HOME="${STEAMLAUNCHY_DATA_HOME:-${XDG_DATA_HOME:-$HOME/.local/share}/steamlaunchy}"

STEAMLAUNCHY_CONF="${STEAMLAUNCHY_CONF:-${STEAMLAUNCHY_CONFIG_HOME}/launchy.env}"
[[ -f "$STEAMLAUNCHY_CONF" ]] && source "$STEAMLAUNCHY_CONF"

STEAMLAUNCHY_DEBUG="${STEAMLAUNCHY_DEBUG:-0}"
STEAMLAUNCHY_INCLUDE_EXPERIMENTAL="${STEAMLAUNCHY_INCLUDE_EXPERIMENTAL:-0}"
STEAMLAUNCHY_PROTON_BIN_NAME="${STEAMLAUNCHY_PROTON_BIN_NAME:-proton}"
STEAMLAUNCHY_STEAM_HOME="${STEAM_COMPAT_CLIENT_INSTALL_PATH:-$HOME/.steam/steam}"

readonly STEAMLAUNCHY_REGEX_IS_PROTON_STABLE='.*/Proton [0-9]+.[0-9]+(.[0-9]+)?$'
readonly STEAMLAUNCHY_REGEX_IS_PROTON_EXPERIMENTAL='.*/Proton.*Experimental$'

log::println() {
    # Usage: log::println "prefix" "string"

    printf -v now '%(%m-%d-%Y %H:%M:%S)T' -1
    printf '%b\n' "[${1:: 4}] ${now} ${0##*/} ${2}"
}

log::warn() {
    # Usage: log::warn "string"

    log::println "WARN" "$*"
}

log::debug() {
    # Usage: log::debug "string"

    [[ $STEAMLAUNCHY_DEBUG -eq 1 ]] && log::println "DEBUG" "$*"
}

log::info() {
    # Usage: log::info "string"

    log::println "INFO" "$*"
}

log::error() {
    log::println "ERROR" "$*"
}

# https://github.com/dylanaraps/pure-bash-bible#split-a-string-on-a-delimiter
util::split() {
    # Usage: util::split "string" "delimiter"

    IFS=$'\n' read -d "" -ra arr <<< "${1//$2/$'\n'}"
    printf '%s\n' "${arr[@]}"
}

# https://github.com/dylanaraps/pure-bash-bible#get-the-base-name-of-a-file-path
util::basename() {
    # Usage: util::basename "path" ["suffix"]

    local tmp

    tmp=${1%"${1##*[!/]}"}
    tmp=${tmp##*/}
    tmp=${tmp%"${2/"$tmp"}"}

    printf '%s\n' "${tmp:-/}"
}

util::new_random_dir() {
    # Usage: util::new_random_dir "path/to/prefix"

    # $RANDOM is an internal Bash function (not a constant) that returns a
    # pseudorandom integer in the range 0 - 32767
    local dirname
    dirname="${RANDOM}${RANDOM}"

    # Support overriding the dirname
    [[ -n "$DESTDIR" ]] && dirname="$DESTDIR"

    # Add '/' suffix
    [[ -n "$1" ]] && set -- "${1}/"

    # Handle collisions
    while [[ -d "${1}${dirname}" ]] && [[ -z "$DESTDIR" ]]; do
        util::new_random_dir "$@"
    done

    mkdir --parent "${1}${dirname}"

    # Print final path
    printf '%s' "${1}${dirname}"
}

proton::set_path() {
    # Usage: proton::set_path

    if [[ -n "$STEAMLAUNCHY_PROTON_PATH" ]]; then
        log::debug "Environment variable STEAMLAUNCHY_PROTON_PATH set to '${STEAMLAUNCHY_PROTON_PATH}'. Continuing..."
        return 0
    fi

    for f in "${STEAMLAUNCHY_STEAM_HOME}/steamapps/common/"*; do
        # Ignore any file that's not a directory
        [[ -d "$f" ]] || continue

        if [[ "$f" =~ $STEAMLAUNCHY_REGEX_IS_PROTON_STABLE ]] || [[ "$f" =~ $STEAMLAUNCHY_REGEX_IS_PROTON_EXPERIMENTAL ]]; then
            [[ -z "$1" ]] || set -- "${*}:"
            set -- "${*}${f}"
        fi
    done

    STEAMLAUNCHY_PROTON_PATH="$@"
    log::debug "Environment variable STEAMLAUNCHY_PROTON_PATH set to '${STEAMLAUNCHY_PROTON_PATH}'"
}

proton::set_version() {
    # Usage: proton::set_version

    if [[ -n "$STEAMLAUNCHY_PROTON_VERSION" ]]; then
        log::debug "Environment variable STEAMLAUNCHY_PROTON_VERSION set to '${STEAMLAUNCHY_PROTON_VERSION}'. Continuing..."
        return 0
    fi

    declare -a arr arr_sorted
    IFS=$'\n' arr=($(util::split "$STEAMLAUNCHY_PROTON_PATH" ":"))

    [[ $STEAMLAUNCHY_INCLUDE_EXPERIMENTAL -eq 0 ]] && for i in "${!arr[@]}"; do
        if [[ "${arr[$i]}" =~ $STEAMLAUNCHY_REGEX_IS_PROTON_EXPERIMENTAL ]]; then
            unset arr[$i]
        fi
    done

    arr_sorted=($(printf '%s ' "${arr[@]}" | sort --numeric-sort))

    # Reuse array because i'm lazy
    IFS=' ' arr=($(util::basename "${arr_sorted[0]}"))

    STEAMLAUNCHY_PROTON_VERSION="${arr[-1]}"
    log::warn "No proton version specified. Defaulting to proton ${STEAMLAUNCHY_PROTON_VERSION}"
}

proton::set_bin() {
    # Usage::set_bin

    if [[ -n "$STEAMLAUNCHY_PROTON_BIN" ]]; then
        log::debug "Environment variable STEAMLAUNCHY_PROTON_BIN set to '${STEAMLAUNCHY_PROTON_BIN}'. Continuing..."
        return 0
    fi

    declare -a arr
    IFS=$'\n' arr=($(util::split "$STEAMLAUNCHY_PROTON_PATH" ":"))

    # Find the proton bin associated with the proton version
    for p in "${arr[@]}"; do
        if [[ "$p" == *"$STEAMLAUNCHY_PROTON_VERSION" ]]; then
            STEAMLAUNCHY_PROTON_BIN="${p}/${STEAMLAUNCHY_PROTON_BIN_NAME}"
            log::debug "Found proton executable '${STEAMLAUNCHY_PROTON_BIN}'"
            return 0
        fi
    done

    if [[ ! -x "$STEAMLAUNCHY_PROTON_BIN" ]]; then
        log::error "File '$STEAMLAUNCHY_PROTON_BIN' not executable."
        return 126
    fi

    log::error "Unable to find proton executable for version '${STEAMLAUNCHY_PROTON_VERSION}'."
    return 2
}

proton::run() {
    # Usage: proton::run

    if [[ -z "$1" ]]; then
        log::error "No arguments specified."
        return 128
    fi

    log::info "Launching $1"
    log::debug "Executing '${STEAMLAUNCHY_PROTON_BIN}' with arguments '${*}'"

    # Run proton. Replace the current process
    STEAM_COMPAT_CLIENT_INSTALL_PATH="${STEAM_COMPAT_CLIENT_INSTALL_PATH:-$STEAMLAUNCHY_STEAM_HOME}" \
    STEAM_COMPAT_DATA_PATH="${STEAM_COMPAT_DATA_PATH:-STEAMLAUNCHY_APPLICATION_HOME}" \
    exec "$STEAMLAUNCHY_PROTON_BIN" run "$@"
}

launchy::setup() {
    if [[ -n "$STEAMLAUNCHY_APPLICATION_PREFIX" ]]; then
        DESTDIR="$STEAMLAUNCHY_APPLICATION_PREFIX"
    fi

    STEAMLAUNCHY_APPLICATION_HOME="$(util::new_random_dir "${STEAMLAUNCHY_DATA_HOME}")"
    unset DESTDIR

    log::info "Application directory '${STEAMLAUNCHY_APPLICATION_HOME}'"

    if [[ ! -d  "${STEAMLAUNCHY_CONFIG_HOME}" ]]; then
        log::info "Creating directory '${STEAMLAUNCHY_CONFIG_HOME}'"
        mkdir --parent "${STEAMLAUNCHY_CONFIG_HOME}"
    fi
}

main() {
    launchy::setup "$1"

    proton::set_path
    proton::set_version
    proton::set_bin

    proton::run "$@"
}

main "$@"
